build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.8
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.9
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: "3.10"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.11
      MINICONDA: C:\Miniconda3

matrix:
  exclude:
    - platform: x86
      PYTHON_VERSION: 3.11

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%
  - ECHO conda --version

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment --channel=conda-forge mmtf-python numpy scipy pandas pytest looseversion importlib_resources python=%PYTHON_VERSION%
  - activate test-environment
  - pip install -e .

test_script:
  - pytest -s -v
